server:
  port: 8010 #服务端口
#  tomcat:
#    max-threads: 5 # 最大线程并发量，默认值为200

spring:
  profiles:
    active: dev # 环境
  application:
    name: service-edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_guli_edu?serverTimezone=GMT%2B8
    username: root
    password: Ren666665
  jackson:
    time-zone: GMT+8 # 规定时间
    date-format: yyyy-MM-dd HH:mm:ss #规定日期时间格式 2000-10-19 23:23:99
  cloud:
    nacos: # nacos
      discovery:
        server-addr: 182.92.227.211:8848 #nacos 服务地址
    sentinel: # sentinel
      transport:
        port: 9010 # 跟控制台交流的端口，可随意指定未使用端口号
        dashboard: 182.92.227.211:8080 # 指定sentinel控制台服务的地址
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 2 #最大空闲连接数
        min-idle: 0 #最小空闲连接数

#Mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #Mybatis日志
  mapper-locations: classpath:com/yuxiang/guli/service/edu/mapper/xml/*.xml # 配置Mapper.Xml文件路径


# 负载均衡策略
#service-oss:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  MaxAutoRetries: 1 # 同一实例最大重试次数，不包括首次调用，默认为0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认为1
  ConnectTimeout: 10000 # 连接建立的超时时长，默认1秒
  ReadTimeout: 10000 # 处理请求的超时时间，默认1秒

#
feign:
  sentinel:
    enabled: true
