server:
  port: 8012
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.227.211:8848 #nacos 服务地址
    sentinel: # sentinel
      transport:
        port: 9012 # 跟控制台交流的端口，可随意指定未使用端口号
        dashboard: 182.92.227.211:8080 # 指定sentinel控制台服务的地址
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
aliyun:
  vod:
    accessKeyId: LTAI4Fzz55y4H2yGh89YMGRp
    accessKeySecret: D1EFQnFqKXIJc1MJIczy0NRCGTPfX1
    templateGroupId: 111 #转码模板组id
    workflowId: 111 #配置的工作流id
