server:
  port: 8011
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.227.211:8848 #nacos 服务地址
    sentinel: # sentinel
      transport:
        port: 9011 # 跟控制台交流的端口，可随意指定未使用端口号
        dashboard: 182.92.227.211:8080 # 指定sentinel控制台服务的地址
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4Fzz55y4H2yGh89YMGRp
    accessKeySecret: D1EFQnFqKXIJc1MJIczy0NRCGTPfX1
    bucketName: video-guli
